
import { PrismaClient } from '../../generated/prisma'
import { unique_random } from '../utils/unique'
import { Request, Response } from 'express'
import client from '../utils/redis'
const prisma = new PrismaClient()

export async function shotner(req: Request, res: Response) {

    try {
        const { ogLink } = req.body

        if (!ogLink) {
            return res.status(400).json({ error: "No link given" })
        }

        try {
            new URL(ogLink)
        } catch (err) {
            return res.status(400).json({ error: "Invalid URL Please dont try to break code" })
        }
        //Check if link already shortend and avoid dupllications
        const isalreadyExists = await prisma.linkmap.findFirst({
            where: { ogLink: ogLink }
        })

        if (isalreadyExists) {
            const short_url = isalreadyExists.newLink
            return res.status(201).json({
                original: ogLink,
                short: `https://${process.env.HOST_DOMAIN}/${short_url}`
            })
        }

        const store = await prisma.linkmap.create({
            data: {
                ogLink: ogLink,
                newLink: 'JUST_WAIT'
                //can cause race conditions issues
            },


        })

        const short_url = unique_random(store.id, 6, 8)

        await prisma.linkmap.update({
            where: { id: store.id },
            data: { newLink: short_url }
        })

       await client.set(short_url, ogLink)

        return res.status(201).json({
            original: ogLink,
            short: `https://${process.env.HOST_DOMAIN}/${short_url}`
        })

    } catch (err) {
        console.error(err)
        res.status(500).json({ error: "failed ot shorten" })
    }


}

export async function redirect(req: Request, res: Response) {
    const { short } = req.params

    try {
        const isCached = await client.get(short)

        if (isCached) {
            console.log('Voila its a hit:', short)
            res.redirect(302, isCached)
        }
        const findOg = await prisma.linkmap.findUnique({
            where: { newLink: short }
        })
        if (!findOg) {
            return res.status(404).send('URL not generated by this service')
        }

        return res.redirect(302, findOg.ogLink)

    } catch (err) {
        console.error(err)
        return res.status(500).send('Server error')
    }


}